### ISSUE TITLE
FeatureRequest: Support `verify=False` argument for requests

### ISSUE THREAD

**Issue by mimi1vx** [os-autoinst/openQA-python-client#15]
Hello,

 som of our instances have self-signed certificates :( so it will be very helpful if openqa_client support requests `verify=False` parameter

**Comment by AdamWill** [comment]
Hi, sorry I didn't follow up on this. Is it still an issue? Can you not just connect to these instances via http instead of https ? The client allows for that (in fact, it defaults to it when connecting to `localhost`).

**Comment by ricardobranco777** [comment]
This option is absolutely needed because `verify` can also hold the path to a certificate file.

In our case we have to apply this hotfix, but only works with a simple certificate and not the system bundle:

https://github.com/SUSE/pcw/pull/311

**Comment by AdamWill** [comment]
OK, I'll try and get to it, then. If anyone wants to send a PR that'd be great too.

**Comment by ricardobranco777** [comment]
> OK, I'll try and get to it, then. If anyone wants to send a PR that'd be great too.

I submitted a less intrusive patch that merges the environment variables.  To achieve `verify=False` this can be done already:

```
import openqa_client.client
client = openqa_client.client.OpenQA_Client(server="https://openqa.suse.de", wait=5, retries=1)
client.session.verify = False
```

So this issue can be closed before merging the PR.
