### ISSUE TITLE
Start using urllib3's retry stuff

### ISSUE THREAD

**Issue by dcermak** [os-autoinst/openQA-python-client#16]
I've stumbled over this comment: 
https://github.com/os-autoinst/openQA-python-client/blob/f227d83dd42c787579d95a03322004b283c02154/src/openqa_client/client.py#L137

openSUSE 13.2 has been EOL for a long, long time now, maybe we can stop implementing this ourselves ;-)

**Comment by AdamWill** [comment]
yeah, but then I have to remember how it works...:D

**Comment by perlpunk** [comment]
We found that the client also retries on 404 responses, which is probably not what users want.
As a result, we currently have the retry feature disabled: https://github.com/openSUSE/qem-bot/pull/79

**Comment by AdamWill** [comment]
https://github.com/os-autoinst/openQA-python-client/pull/34 kind of addresses this. I wrote all the code to use `urllib3.util.Retry` instead, then realized that was adding two more explicit imports plus more lines of code than it takes to just implement retries in-line, so I had second thoughts. :D So instead, we update the comment, and add a list of sensible (I hope) status codes to retry on, which should solve the "retrying on 404" problem. Let me know what you think.

**Comment by AdamWill** [comment]
Gonna count https://github.com/os-autoinst/openQA-python-client/pull/34 as effectively addressing this, even though it doesn't do exactly what was suggested.
