### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by jayvdb** [os-autoinst/openQA-python-client#8]
Could this be uploaded to PyPI to make packaging easier?

**Comment by AdamWill** [comment]
If it helps you, I could, sure. I do the Fedora package just from the github releases:

https://src.fedoraproject.org/rpms/python-openqa_client/blob/master/f/python-openqa_client.spec

would that not work for you?

**Comment by AdamWill** [comment]
Actually, I needed this myself just now for tox purposes, so I just [did it](https://pypi.org/project/openqa-client/).
